type AgentConfig = { model?: string; effort?: string };
type AgentMessage = { id: string; text: string; at: string };
type StreamingAgentMessage = { itemId: string; text: string; startedAt: string; updatedAt: string };
type AgentActivity = { id: string; tool: string; status: string; at: string };
type Capability = { available: boolean; reason?: string };
type ExecutionTargetCapabilities = { pause: Capability; stop: Capability; retry: Capability };
export type ExecutionCapabilities = ExecutionTargetCapabilities & { nodes: Record<string, ExecutionTargetCapabilities> };
export type AgentCapabilities = {
  observe: Capability;
  steer: Capability;
  followUp: Capability;
  interrupt: Capability;
  retry: Capability;
  modelOverride: Capability;
};
export type AdapterDescriptor = { harness: string; transport: string; mode: "live" | "observed"; label: string };
type ExecutionAuthority = "authoritative" | "declared" | "legacy" | "suspected";
type ExecutionNodeKind = "stage" | "action" | "verifier" | "wait" | "subgraph" | "terminal";
type ExecutionEdgeKind = "normal" | "success" | "failure" | "loop-back";
type ExecutionNode = { id: string; label: string; kind: ExecutionNodeKind; description?: string; subgraphId?: string };
type ExecutionEdge = { id: string; from: string; to: string; kind: ExecutionEdgeKind; condition?: string };
type NodeActivation = {
  id: string;
  nodeId: string;
  iteration: number;
  status: "queued" | "running" | "waiting" | "passed" | "failed" | "stopped";
  threadIds: string[];
  startedAt: string;
  completedAt?: string;
  summary?: string;
};
export type ExecutionGraphState = {
  id: string;
  ownerThreadId: string;
  label?: string;
  objective?: string;
  policy?: { verifier?: string; maxTokens?: number; maxIterations?: number };
  source: { kind: "harness" | "watchdog" | "operator" | "legacy" | "inferred"; label?: string };
  authority: ExecutionAuthority;
  parentExecutionId?: string;
  parentNodeId?: string;
  nodes: ExecutionNode[];
  edges: ExecutionEdge[];
  entryNodeIds: string[];
  terminalNodeIds: string[];
  status: "pending" | "running" | "waiting" | "blocked" | "completed" | "failed" | "stopped";
  incompleteReason?: string;
  iteration: number;
  activations: NodeActivation[];
  traversals: Array<{ id: string; edgeId: string; from: string; to: string; iteration: number; at: string }>;
  activeNodeIds: string[];
  startedAt?: string;
  completedAt?: string;
  stopReason?: string;
  evidence: Array<{ id: string; iteration: number; summary: string; source: string; threadId: string; nodeId?: string; at: string }>;
  verification: { status: "not-run" | "running" | "passed" | "failed"; summary?: string; at?: string };
  usedTokens: number;
  warnings: string[];
};

export type AgentState = {
  threadId: string;
  parentThreadId?: string;
  nickname?: string;
  role?: string;
  kind?: "root" | "native-child" | "subprocess-worker" | "independent-session";
  agentPath?: string;
  status: string;
  activeTurnId?: string;
  totalTokens?: number;
  inputTokens?: number;
  outputTokens?: number;
  costUsd?: number;
  requested?: AgentConfig & { prompt?: string };
  effective?: AgentConfig;
  latestActivity?: { tool: string; status: string };
  activities?: AgentActivity[];
  activityCount?: number;
  task?: string;
  latestMessage?: string;
  messages?: AgentMessage[];
  messageCount?: number;
  streamingMessage?: StreamingAgentMessage;
  execution?: { executionId: string; nodeId: string; activationId: string };
  startedAt?: string;
  lastActivityAt?: string;
  lastTurnCompletedAt?: string;
};

export type LoopState = {
  threadId: string;
  objective?: string;
  iteration: number;
  activeTurnId?: string;
  phase: "plan" | "execute" | "verify" | "done" | "blocked";
  verifier?: string;
  verification: { status: "not-run" | "running" | "passed" | "failed"; summary?: string; at?: string };
  evidence: Array<{ id: string; iteration: number; summary: string; source: string; agentThreadId: string; at: string }>;
  budget: { maxTokens?: number; maxIterations?: number; usedTokens: number };
  warnings: string[];
};

export type RunSnapshot = {
  startedAt: string;
  mode: "live" | "observed";
  agents: AgentState[];
  loops: LoopState[];
  executions: ExecutionGraphState[];
  adapter?: AdapterDescriptor;
  capabilities?: Record<string, AgentCapabilities>;
  executionCapabilities?: Record<string, ExecutionCapabilities>;
};
type RunListItem = {
  runId: string;
  projectName: string;
  cwd: string;
  startedAt: string;
  adapter: AdapterDescriptor;
  agents: number;
  activeAgents: number;
  objective?: string;
};
export type DashboardState = {
  connected: boolean;
  snapshot: RunSnapshot;
  message?: string;
  runs: RunListItem[];
  selectedRunId?: string;
};
